# Site settings
title: Cotize Blog
email: michel.barret@gmail.com
description: "Le blog de développement de Cotize"
baseurl: ""
url: "https://barmic.github.io/cotize/"
#twitter_username: jekyllrb
github_username:  barmic

# Build settings
markdown: kramdown
permalink: pretty
