---
- hosts: cotize
  vars:
    package: BonsComptes-jar-with-dependencies.jar
    subdomain: cotize2
    domain: barmic.eu
    proxy_port: 5000
    become_method: su
    php: no
  tasks:
  - name: Upload package
    copy: src=backend/target/{{ package }} dest=/opt/cotize
    become: true
  - name: Upload config
    copy: src=infra/config.json dest=/opt/cotize
    become: true
  - name: Upload statics files
    synchronize: src=frontend/ dest=/opt/cotize/public
  - name: Restart cotize
    service: name=cotize state=restarted
    become: true
  - name: Restart nginx
    service: name=nginx state=restarted
    become: true